name: Release Assets
on:
  release:
    types: [published]

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Build project
      run: |-
        ./gradlew build -x test
        mv lib/build/libs/lib.jar kafka-connect-opensearch.jar
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: kafka-connect-opensearch.jar
